import 'package:drift/drift.dart';
import 'package:lauschi/core/database/app_database.dart' show Tile, TileItem;

// ---------------------------------------------------------------------------
// DB table naming vs Dart class naming
//
// The DB tables are called `Groups` and `Cards` (legacy names). The Dart data
// classes generated by Drift are `Tile` and `TileItem` via @DataClassName.
//
// We kept the DB table names to avoid a schema migration. DB says
// "groups"/"cards", Dart says "Tile"/"TileItem", user sees "Kacheln".
//
// Nesting: Groups.parentTileId enables recursive tile nesting. A tile
// with parentTileId = null is a root tile (visible on home screen). A tile
// with parentTileId set is a child (visible inside its parent). Nesting
// depth is unrestricted; the UI decides how deep to render.
// ---------------------------------------------------------------------------

/// Tracks subscribed external shows for automated sync.
///
/// A subscription links an external show (e.g. ARD programSet) to a [Tile].
/// The sync service periodically checks for new episodes and adds them
/// as [TileItem]s to the linked [Tile].
@DataClassName('ShowSubscription')
class ShowSubscriptions extends Table {
  IntColumn get id => integer().autoIncrement()();

  /// Provider identifier: 'ard_audiothek', etc.
  TextColumn get provider => text()();

  /// External show/programSet ID (string for cross-provider compat).
  TextColumn get externalShowId => text()();

  /// Show title (cached from API for display without network).
  TextColumn get title => text()();

  /// Show artwork URL (cached).
  TextColumn get coverUrl => text().nullable()();

  /// Linked Tile ID. DB column is still "group_id" (legacy).
  /// Cascade delete: removing a tile removes its subscriptions.
  TextColumn get groupId =>
      text().references(Groups, #id, onDelete: KeyAction.cascade)();

  /// Max episodes to keep. Null = all published.
  /// For rolling shows (Betthupferl, Sandmännchen), cap at e.g. 20.
  IntColumn get maxEpisodes => integer().nullable()();

  /// When we last synced this subscription.
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();

  /// Last known `lastItemAdded` from the external API.
  /// Used for change detection: if the API value is newer, fetch new episodes.
  DateTimeColumn get remoteLastItemAdded => dateTime().nullable()();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A tile on the kid's home screen. Contains [TileItem]s (episodes, tracks).
///
/// Tiles can be nested: a tile with [parentTileId] set is a child tile that
/// appears inside its parent rather than on the home screen. This lets parents
/// group related content (e.g. all Senta albums under a "Senta" parent tile).
/// Nesting can be arbitrarily deep (a parent can itself be a child).
///
/// DB table name: `groups` (legacy naming, Dart data class is `Tile`).
@DataClassName('Tile')
class Groups extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get coverUrl => text().nullable()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Content type: 'hoerspiel' (default), 'music', 'audiobook'.
  /// Affects playback behaviour (auto-advance, shuffle, progress tracking).
  TextColumn get contentType =>
      text().withDefault(const Constant('hoerspiel'))();

  /// Provider for this tile's content. Null for mixed/manual tiles.
  /// Used to determine playback behaviour and show provider badges.
  /// Values: 'spotify', 'ard_audiothek', 'apple_music'.
  TextColumn get provider => text().nullable()();

  /// External show ID — content identity FK. For ARD: programSet numeric ID.
  /// For Apple Music (future): show/station ID.
  /// Null for manually-curated tiles.
  ///
  /// This is the identity link ("this tile = ARD show X"), NOT sync state.
  /// All sync automation (lastSyncedAt, maxEpisodes, etc.) lives in
  /// ShowSubscriptions.
  TextColumn get externalShowId => text().nullable()();

  /// Parent tile ID for nesting. Null means this is a root tile (shows on
  /// the kid's home screen). Non-null means this tile is nested inside the
  /// parent and only visible when the parent is opened.
  ///
  /// Self-referencing FK. Cascade delete: removing a parent removes its
  /// entire subtree. Nesting depth is unrestricted.
  TextColumn get parentTileId =>
      text().nullable().references(Groups, #id, onDelete: KeyAction.cascade)();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

@DataClassName('NfcTag')
class NfcTags extends Table {
  /// Auto-incrementing primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Hardware UID of the NFC tag (hex string). Unique per physical tag.
  TextColumn get tagUid => text().unique()();

  /// What this tag points to: 'tile' or 'item'.
  /// DB values still 'group'/'card' for backwards compat — mapped in code.
  TextColumn get targetType => text()();

  /// ID of the tile or item this tag triggers.
  TextColumn get targetId => text()();

  /// User-provided label (e.g. "Yakari-Figur").
  TextColumn get label => text().nullable()();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A playable content item inside a [Tile] (episode, album, track).
///
/// DB table name: `cards` (legacy, will be renamed to `tile_items`).
/// The `groupId` column is the FK to the parent [Tile].
@DataClassName('TileItem')
class Cards extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get customTitle => text().nullable()();
  TextColumn get coverUrl => text().nullable()();
  TextColumn get customCoverPath => text().nullable()();

  // 'album' | 'playlist' | 'track' | 'podcast'
  TextColumn get cardType => text()();

  // Serialized ProviderType value: 'spotify', 'ard_audiothek', etc.
  TextColumn get provider => text().withDefault(const Constant('spotify'))();

  // e.g. 'spotify:album:4aawyAB9vmqN3uQ7FjRGTy'
  TextColumn get providerUri => text()();

  // Comma-separated Spotify artist IDs as returned by the search API.
  // Stored at insert time so retroactive catalog matching can use artist ID
  // phase-2 even for albums whose titles omit the series name.
  TextColumn get spotifyArtistIds => text().nullable()();

  // Parent tile (nullable — ungrouped items appear at top level).
  // DB column is still "group_id" (legacy).
  TextColumn get groupId => text().nullable().references(Groups, #id)();
  IntColumn get episodeNumber => integer().nullable()();
  BoolColumn get isHeard => boolean().withDefault(const Constant(false))();

  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Total number of tracks in this album (from Spotify at insert time).
  /// Used to compute playback progress and detect album completion.
  IntColumn get totalTracks => integer().withDefault(const Constant(0))();

  /// When this content expires and becomes unavailable.
  /// Null means permanent (Spotify, some ARD shows like Figarino/Kakadu).
  DateTimeColumn get availableUntil => dateTime().nullable()();

  /// Direct audio URL for non-SDK providers (ARD Audiothek, local, etc.).
  /// Null for Spotify/Apple Music (playback via SDK, not direct URL).
  TextColumn get audioUrl => text().nullable()();

  /// Total duration in milliseconds. For Spotify this comes from the SDK
  /// at runtime; for direct-play providers it's stored at insert time
  /// since there's no SDK to query.
  IntColumn get durationMs => integer().withDefault(const Constant(0))();

  /// When this item was marked unavailable (content removed, license expired).
  /// Null = available. Non-null = unavailable since this date.
  /// Used for Spotify/Apple Music (runtime detection) and ARD (post-add expiry).
  /// The date enables the 7-day recheck window for auto-recovery.
  DateTimeColumn get markedUnavailable => dateTime().nullable()();

  // Playback resume state
  TextColumn get lastTrackUri => text().nullable()();

  /// 1-based track number within the album, stored alongside lastTrackUri
  /// so progress can be computed without an API lookup.
  IntColumn get lastTrackNumber => integer().withDefault(const Constant(0))();
  IntColumn get lastPositionMs => integer().withDefault(const Constant(0))();
  DateTimeColumn get lastPlayedAt => dateTime().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
