import 'package:drift/drift.dart';

// ---------------------------------------------------------------------------
// DB table naming vs Dart class naming
//
// The DB tables are called `Groups` and `Cards` (legacy names). The Dart data
// classes generated by Drift are `Tile` and `TileItem` via @DataClassName.
//
// We kept the DB table names to avoid a schema migration. A future migration
// will rename them to `tiles` and `tile_items` with a parent_id column for
// recursive nesting. Until then: DB says "groups"/"cards", Dart says
// "Tile"/"TileItem", user sees "Kacheln".
// ---------------------------------------------------------------------------

/// Tracks subscribed external shows for automated sync.
///
/// A subscription links an external show (e.g. ARD programSet) to a [Tile].
/// The sync service periodically checks for new episodes and adds them
/// as [TileItem]s to the linked [Tile].
@DataClassName('ShowSubscription')
class ShowSubscriptions extends Table {
  IntColumn get id => integer().autoIncrement()();

  /// Provider identifier: 'ard_audiothek', etc.
  TextColumn get provider => text()();

  /// External show/programSet ID (string for cross-provider compat).
  TextColumn get externalShowId => text()();

  /// Show title (cached from API for display without network).
  TextColumn get title => text()();

  /// Show artwork URL (cached).
  TextColumn get coverUrl => text().nullable()();

  /// Linked Tile ID. DB column is still "group_id" (legacy).
  /// Cascade delete: removing a tile removes its subscriptions.
  TextColumn get groupId =>
      text().references(Groups, #id, onDelete: KeyAction.cascade)();

  /// Max episodes to keep. Null = all published.
  /// For rolling shows (Betthupferl, Sandmännchen), cap at e.g. 20.
  IntColumn get maxEpisodes => integer().nullable()();

  /// When we last synced this subscription.
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();

  /// Last known `lastItemAdded` from the external API.
  /// Used for change detection: if the API value is newer, fetch new episodes.
  DateTimeColumn get remoteLastItemAdded => dateTime().nullable()();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A tile on the kid's home screen. Contains [TileItem]s (episodes, tracks).
///
/// DB table name: `groups` (legacy, will be renamed to `tiles` in a future
/// migration that also adds parent_id for recursive nesting).
@DataClassName('Tile')
class Groups extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get coverUrl => text().nullable()();
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Content type: 'hoerspiel' (default), 'music', 'audiobook'.
  /// Affects playback behaviour (auto-advance, shuffle, progress tracking).
  TextColumn get contentType =>
      text().withDefault(const Constant('hoerspiel'))();

  /// Provider for this tile's content. Null for mixed/manual tiles.
  /// Used to determine playback behaviour and show provider badges.
  /// Values: 'spotify', 'ard_audiothek', 'apple_music'.
  TextColumn get provider => text().nullable()();

  /// External show ID — content identity FK. For ARD: programSet numeric ID.
  /// For Apple Music (future): show/station ID.
  /// Null for manually-curated tiles.
  ///
  /// This is the identity link ("this tile = ARD show X"), NOT sync state.
  /// All sync automation (lastSyncedAt, maxEpisodes, etc.) lives in
  /// ShowSubscriptions.
  TextColumn get externalShowId => text().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

@DataClassName('NfcTag')
class NfcTags extends Table {
  /// Auto-incrementing primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Hardware UID of the NFC tag (hex string). Unique per physical tag.
  TextColumn get tagUid => text().unique()();

  /// What this tag points to: 'tile' or 'item'.
  /// DB values still 'group'/'card' for backwards compat — mapped in code.
  TextColumn get targetType => text()();

  /// ID of the tile or item this tag triggers.
  TextColumn get targetId => text()();

  /// User-provided label (e.g. "Yakari-Figur").
  TextColumn get label => text().nullable()();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// A playable content item inside a [Tile] (episode, album, track).
///
/// DB table name: `cards` (legacy, will be renamed to `tile_items`).
/// The `groupId` column is the FK to the parent [Tile].
@DataClassName('TileItem')
class Cards extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get customTitle => text().nullable()();
  TextColumn get coverUrl => text().nullable()();
  TextColumn get customCoverPath => text().nullable()();

  // 'album' | 'playlist' | 'track' | 'podcast'
  TextColumn get cardType => text()();

  // 'spotify' | 'apple_music' | 'local'
  TextColumn get provider => text().withDefault(const Constant('spotify'))();

  // e.g. 'spotify:album:4aawyAB9vmqN3uQ7FjRGTy'
  TextColumn get providerUri => text()();

  // Comma-separated Spotify artist IDs as returned by the search API.
  // Stored at insert time so retroactive catalog matching can use artist ID
  // phase-2 even for albums whose titles omit the series name.
  TextColumn get spotifyArtistIds => text().nullable()();

  // Parent tile (nullable — ungrouped items appear at top level).
  // DB column is still "group_id" (legacy).
  TextColumn get groupId => text().nullable().references(Groups, #id)();
  IntColumn get episodeNumber => integer().nullable()();
  BoolColumn get isHeard => boolean().withDefault(const Constant(false))();

  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Total number of tracks in this album (from Spotify at insert time).
  /// Used to compute playback progress and detect album completion.
  IntColumn get totalTracks => integer().withDefault(const Constant(0))();

  /// When this content expires and becomes unavailable.
  /// Null means permanent (Spotify, some ARD shows like Figarino/Kakadu).
  DateTimeColumn get availableUntil => dateTime().nullable()();

  /// Direct audio URL for non-SDK providers (ARD Audiothek, local, etc.).
  /// Null for Spotify/Apple Music (playback via SDK, not direct URL).
  TextColumn get audioUrl => text().nullable()();

  /// Total duration in milliseconds. For Spotify this comes from the SDK
  /// at runtime; for direct-play providers it's stored at insert time
  /// since there's no SDK to query.
  IntColumn get durationMs => integer().withDefault(const Constant(0))();

  // Playback resume state
  TextColumn get lastTrackUri => text().nullable()();

  /// 1-based track number within the album, stored alongside lastTrackUri
  /// so progress can be computed without an API lookup.
  IntColumn get lastTrackNumber => integer().withDefault(const Constant(0))();
  IntColumn get lastPositionMs => integer().withDefault(const Constant(0))();
  DateTimeColumn get lastPlayedAt => dateTime().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
